# Basic
title: Htroy's HomePage
subtitle: 
welcome_message: 
description: Welcome to Htroy.com!
creator: <a href="http://htroy.com">@Htroy</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Article
    description: Visit Article

# Navigation buttons in the front page.
nav:
    - {title: Github, description: Go to my Github, url: 'https://github.com/FsHtroy'}
    - {title: AS139216, description: Go to my AS139216.network, url: 'https://home.139216.network/'}

# Pagination
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page/:num/"

# Comment
comment:
    disqus: 
    # duoshuo: 
    
# Social
social:
    weibo: -HTroy
    github: FsHtroy

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
